### ISSUE TITLE
Release 0.2.2 in packagist (perhaps make the project auto-updated)

### ISSUE THREAD

**Issue by rogeriopradoj** [Respect/Data#11]

**Comment by henriquemoody** [comment]
It's awkward. The credentials are fine, I will recreate the release to see what happens.

**Comment by henriquemoody** [comment]
0.2.2 is now available on Packagist (https://packagist.org/packages/respect/data#0.2.2), thanks for reporting.

**Comment by williamespindola** [comment]
Thanks @henriquemoody but now the Respect\Relational must require Data 0.2.2 to work

**Comment by henriquemoody** [comment]
I will be glad if you send a pull request for that, @williamespindola!

**Comment by williamespindola** [comment]
[Done](https://github.com/Respect/Relational/commit/47811cca4400d2c96288b109d7e312028e158989)

**Comment by rogeriopradoj** [comment]
Trying to make it a less strict: https://github.com/Respect/Relational/pull/62
